#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

# zones
define trusted = { "lo", "br-nat", "docker*", "podman*", "eth*", "enp*", "enx*", "tun*", "wg*", "tailscale*" }
define untrusted = { "br-ext", "wlan*", "wlp*" }

destroy table inet filter

table inet filter {
  chain incoming {
    type filter hook input priority filter
    policy drop
    ct state { established, related } accept
    iifname $trusted accept
    limit rate 1/second reject with icmpx type admin-prohibited
  }

  chain forward {
    type filter hook forward priority filter
    policy drop
    ct state { established, related } accept
    iifname $trusted accept
    limit rate 1/second reject with icmpx type admin-prohibited
  }

  chain output {
    type filter hook output priority filter
    policy accept
  }
}

destroy table inet nat

table inet nat {
  chain prerouting {
    type nat hook prerouting priority filter
    policy accept
  }

  chain postrouting {
    type nat hook postrouting priority filter
    policy accept
    oifname != $trusted masquerade random
  }
}
